import os

from dotenv import load_dotenv
from openai import OpenAI, OpenAIError

from services.RAG_system.rag import ask_rag

load_dotenv()



class Companion:
    """
    AI assistant that consumes RAG systems to retrieve relevant information
    and provide contextualized answers to frontend users.
    """
    def __init__(self):
        """
        Initialize the OpenAI client using the configured API key.
        """
        self.client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    
    
    def answer(self, question: str) -> str:
        """
        Generate an answer using the user's question and RAG context.
        Args:
            question: User question received from the frontend.
        Returns:
            A contextualized answer generated by the language model.
        Raises:
            RuntimeError: If the OpenAI service fails or returns no content.
        """
        context = self.consume_rag(question)
        if not context.strip():
            return "I could not find relevant information for this question."
        
        try:
            response = self.client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are a portfolio assistant. "
                            "Answer using only the provided context. "
                            "If the answer is not in the context, say so."
                        ),
                    },
                    {
                        "role": "user",
                        "content": f"""Context:{context} 
                                        Question:{question}""",
                    },
                ],
            )
            
        except OpenAIError as error:
            raise RuntimeError(
                "The assistant service is unavailable."
            ) from error
            
        content = response.choices[0].message.content
        if content is None:
            raise RuntimeError("The assistant returned an empty response.")
        return content
    
    
    def consume_rag(self, question: str) -> str:
        """
        Retrieve relevant context from the RAG system.
        Args:
            question: User question used to search the knowledge base.
        Returns:
            A string containing the retrieved document context.
        Raises:
            ValueError: If the question is empty.
        """
        if not question.strip():
            raise ValueError("The question cannot be empty.")
        documents = ask_rag(question)
        context = "\n\n".join(
            document.page_content
            for document in documents
        )
        return context